Enlarge fullscreen view
scm-manager/scm-statistic-plugin pull request #37
Opened 2022-02-10 14:58 UTC by fscholdei

## Proposed changes

Enlarge fullscreen view

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [x] PR is well described and the description can be used as a commit message on squash
- [x] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [x] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2022-02-16 13:56 UTC, Pilopa requested changes

2022-02-16 13:56 UTC, Pilopa commented on src/main/js/charts/Chart.tsx
> +  render: (props: RenderProps) => any;
Please replace all instances of `any`, where possible.

2022-02-16 15:28 UTC, fscholdei commented on src/main/js/charts/CommitsPerAuthor.tsx
>    options: any;
```suggestion
  options: unknown;
```

2022-02-16 15:30 UTC, fscholdei commented on src/main/js/charts/Chart.tsx
>    render: (props: RenderProps) => any;
```suggestion
  render: (props: RenderProps) => unknown;
```

2022-02-17 12:51 UTC, Pilopa commented
The type changes and conversions to functional components are getting out of hand. In my opinion, and after discussing it with the team, I would suggest to only apply the changes in the [Enlarge fullscreen view](https://github.com/scm-manager/scm-statistic-plugin/pull/37/commits/f12c104c9189da2cb37b6ddd47f3f167d8d794d5) and [Add changelog entry](https://github.com/scm-manager/scm-statistic-plugin/pull/37/commits/94a8c30e3a09e3d138679944522b54a1f5342118) commits. Everything else should be reverted, if at all possible.

2022-02-17 13:17 UTC, Pilopa approved these changes

2022-02-17 13:22 UTC, merged